import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/games">
        <a className="text-5xl max-w-sm rounded shadow-lg justify-between">  
          Games
        </a>
      </Link>
      <br/>
      <br/>
      <Link href="/teams">
        <a className="text-5xl max-w-sm rounded shadow-lg justify-between">  
          Teams
        </a>
      </Link>
    </div>
  )
}
